Repository esnya/ResoniteMetricsCounter, pull requests merged in 2025-01, with the labels that each got.

#12 Stage Options
  ResoniteMetricsCounter/Metrics/MetricsCounter.cs
  ResoniteMetricsCounter/ResoniteMetricsCounterMod.cs
  ResoniteMetricsCounter/UIX/Item/MetricItemBase.cs
  ResoniteMetricsCounter/UIX/MetricsPanel.cs
  ResoniteMetricsCounter/UIX/Pages/DetailedMetricsPanelPage.cs
  ResoniteMetricsCounter/UIX/Pages/ObjectRootPage.cs
  ResoniteMetricsCounter/Utils/WorldElementHelper.cs
Labels: enhancement

#15 UI improvement
  ResoniteMetricsCounter/Metrics/MetricsCounter.cs
  ResoniteMetricsCounter/Patch/Metric_Profiler_Patch.cs
  ResoniteMetricsCounter/UIX/Item/MetricItemBase.cs
  ResoniteMetricsCounter/UIX/Item/MetricPageItemBase.cs
  ResoniteMetricsCounter/UIX/MetricColumnDefinition.cs
  ResoniteMetricsCounter/UIX/MetricsPanel.cs
  ResoniteMetricsCounter/UIX/Pages/DetailedMetricsPanelPage.cs
  ResoniteMetricsCounter/UIX/Pages/DetailedPage.cs
  ResoniteMetricsCounter/UIX/Pages/HierarchyPage.cs
  ResoniteMetricsCounter/UIX/Pages/IMetricsPage.cs
  ResoniteMetricsCounter/UIX/Pages/MetricsPageBase.cs
  ResoniteMetricsCounter/UIX/Pages/ObjectRootPage.cs
  ResoniteMetricsCounter/Utils/Constants.cs
Labels: enhancement

#16 Feature/config write file
  ResoniteMetricsCounter/Metrics/MetricsCounter.cs
  ResoniteMetricsCounter/ResoniteMetricsCounterMod.cs
Labels: enhancement

#20 Added feature to restart profiler after it has been stopped.
  ResoniteMetricsCounter/ResoniteMetricsCounterMod.cs
  ResoniteMetricsCounter/UIX/MetricsPanel.cs
Labels: enhancement, good first issue

#21 fix: 🐛 Add update interval configuration to suppress sync messages
  ResoniteMetricsCounter/Metrics/MetricStage.cs
  ResoniteMetricsCounter/ResoniteMetricsCounterMod.cs
  ResoniteMetricsCounter/UIX/MetricsPanel.cs
Labels: bug, enhancement
